<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Fawry</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fawry.Domain\Fawry.Domain.csproj" />
    <ProjectReference Include="..\Fawry.Application.Contracts\Fawry.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="9.1.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="9.1.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="9.1.0" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="9.1.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="9.1.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="9.1.0" />
  </ItemGroup>

</Project>
